# Generated by Django 5.1.4 on 2025-01-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_App', '0002_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='added_by',
        ),
    ]
