# Generated by Django 5.1.4 on 2025-01-11 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_App', '0003_rename_user_id_product_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Product_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
